### ISSUE TITLE
Bug: Error detected while processing CursorMoved Autocommands

### ISSUE THREAD

**Issue by vunhatchuong** [wllfaria/scheming.nvim#13]
```
Error detected while processing CursorMoved Autocommands for "<buffer=10>":
Error executing lua callback: ...cal/nvim-data/lazy/scheming.nvim/lua/scheming/loader.lua:34: attempt to call field 'setup' (a nil value)                       
stack traceback:    ...cal/nvim-data/lazy/scheming.nvim/lua/scheming/loader.lua:34: in function 'setup_scheme'
                    ...l/nvim-data/lazy/scheming.nvim/lua/scheming/commands.lua:48: in function <...l/nvim-data/lazy/scheming.nvim/lua/scheming/commands.lua:46>  
```
![image](https://github.com/wllfaria/scheming.nvim/assets/20581504/96d80a9e-fc0b-41a9-ae00-719c521d5b8b)

This seems to happen at the 3rd+x item, the number in `"<buffer=10>"` is different each time, sometimes 3 or 5.

**Comment by wllfaria** [comment]
thank you for reporting this, I've investigated and this should be fixed by [#f18fe3c](https://github.com/wllfaria/scheming.nvim/commit/f18fe3cc4a7384be51ae0dd9edbc369753db51d7). Let me know if you have any further problems
