### ISSUE TITLE
Display available variant for a theme

### ISSUE THREAD

**Issue by vunhatchuong** [wllfaria/scheming.nvim#15]
Currently the plugin doesn't display available variants, for example: Catppuccin has Mocha, Frappe, Latte.

**Comment by wllfaria** [comment]
Hey, thanks for issuing this request, as for catppuccin, you can use the configuration table of the theme to tell the variant, like so:

```lua
schemes = {
  catppuccin = {
    flavour = "latte",
  },
}
```

![image](https://github.com/wllfaria/scheming.nvim/assets/43209783/03dbd5b7-91f0-4519-9f19-30d7992b6fe7)
